// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package proposals

import (
	"api/api/proposals"
)

type ControllerUser struct{}

func NewUser() proposals.IProposalsUser {
	return &ControllerUser{}
}

type ControllerAuth struct{}

func NewAuth() proposals.IProposalsAuth {
	return &ControllerAuth{}
}



type ControllerManage struct{}

func NewManage() proposals.IProposalsManage {
	return &ControllerManage{}
}
