// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"api/internal/dao/internal"
)

// internalSliverUserDao is an internal type for wrapping the internal DAO implementation.
type internalSliverUserDao = *internal.SliverUserDao

// sliverUserDao is the data access object for the table sliver_user.
// You can define custom methods on it to extend its functionality as needed.
type sliverUserDao struct {
	internalSliverUserDao
}

var (
	// SliverUser is a globally accessible object for table sliver_user operations.
	SliverUser = sliverUserDao{
		internal.NewSliverUserDao(),
	}
)

// Add your custom methods and functionality below.
