// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"api/internal/dao/internal"
)

// internalSliverPlanDao is an internal type for wrapping the internal DAO implementation.
type internalSliverPlanDao = *internal.SliverPlanDao

// sliverPlanDao is the data access object for the table sliver_plan.
// You can define custom methods on it to extend its functionality as needed.
type sliverPlanDao struct {
	internalSliverPlanDao
}

var (
	// SliverPlan is a globally accessible object for table sliver_plan operations.
	SliverPlan = sliverPlanDao{
		internal.NewSliverPlanDao(),
	}
)

// Add your custom methods and functionality below.
