// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"api/internal/dao/internal"
)

// internalSliverCommentsDao is an internal type for wrapping the internal DAO implementation.
type internalSliverCommentsDao = *internal.SliverCommentsDao

// sliverCommentsDao is the data access object for the table sliver_comments.
// You can define custom methods on it to extend its functionality as needed.
type sliverCommentsDao struct {
	internalSliverCommentsDao
}

var (
	// SliverComments is a globally accessible object for table sliver_comments operations.
	SliverComments = sliverCommentsDao{
		internal.NewSliverCommentsDao(),
	}
)

// Add your custom methods and functionality below.
