// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"api/internal/dao/internal"
)

// internalSliverProposalsDao is an internal type for wrapping the internal DAO implementation.
type internalSliverProposalsDao = *internal.SliverProposalsDao

// sliverProposalsDao is the data access object for the table sliver_proposals.
// You can define custom methods on it to extend its functionality as needed.
type sliverProposalsDao struct {
	internalSliverProposalsDao
}

var (
	// SliverProposals is a globally accessible object for table sliver_proposals operations.
	SliverProposals = sliverProposalsDao{
		internal.NewSliverProposalsDao(),
	}
)

// Add your custom methods and functionality below.
