// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"api/internal/dao/internal"
)

// internalSliverWalletDao is an internal type for wrapping the internal DAO implementation.
type internalSliverWalletDao = *internal.SliverWalletDao

// sliverWalletDao is the data access object for the table sliver_wallet.
// You can define custom methods on it to extend its functionality as needed.
type sliverWalletDao struct {
	internalSliverWalletDao
}

var (
	// SliverWallet is a globally accessible object for table sliver_wallet operations.
	SliverWallet = sliverWalletDao{
		internal.NewSliverWalletDao(),
	}
)

// Add your custom methods and functionality below.
