// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package comments

import (
	"api/api/comments"
)

type ControllerV1 struct{}

func NewV1() comments.ICommentsV1 {
	return &ControllerV1{}
}

type ControllerAuth struct{}

func NewAuth() comments.ICommentsAuth {
	return &ControllerAuth{}
}
